FileInput: добавлена иконка и возможность передачи экшена для удалени…
vitalygashkov/krit-ui pull request #7
Opened 2024-10-01 19:51 UTC by jeymix

…я файла.

2024-10-01 20:07 UTC, jdeuterium commented on lib/components/ui/input.tsx
> +            !shouldWrapWithRelative ? className : rightIcon ? 'truncate line-clamp-1 pr-14' : 'truncate line-clamp-1 pr-8',
`truncate line-clamp-1 pr-8` на 24 строку
`!shouldWrapWithRelative && className,` это оставить как было
а с rightIcon можно так `rightIcon && pr-14`

2024-10-02 03:59 UTC, vitalygashkov requested changes

2024-10-02 03:59 UTC, vitalygashkov commented on lib/components/ui/file-input.tsx
> +    const getRightIconGroup = (onFileRemove?: () => void) => (
onFileRemove можно не передавать, так как он глобально доступен в компоненте. В целом можно вообще эту верстку оставить прямо в пропсе rightIcon. А то компонент маленький, на 50 строчек, поэтому так даже легче читать код будет, как мне кажется.

```suggestion
    const renderRightIconGroup = () => (
```

2024-10-02 04:49 UTC, vitalygashkov approved these changes

2024-10-02 05:05 UTC, merged